trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: 'your-app'
        dockerfile: 'Dockerfile'
        containerRegistry: 'your-acr'

- stage: Deploy
  jobs:
  - job: DeployToK8s
    steps:
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'your-aks'
