apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto-redes-deployment
  labels:
    app: proyecto-redes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proyecto-redes
  template:
    metadata:
      labels:
        app: proyecto-redes
    spec:
      containers:
      - name: proyecto-redes
        image: trascendant/proyecto-redes:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: proyecto-redes-service
spec:
  selector:
    app: proyecto-redes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer