<<<<<<< HEAD
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
=======

>>>>>>> cc618e95272674981edb9406818e5c3922c40e24
